// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionStatus } from "./SessionStatus";

/**
 * §G.2 `ai_sessions` row mapping.
 */
export type AiSession = { id: string, workspaceId: string, cliKind: string, 
/**
 * §G.2 `auto | manual`.
 */
source: string, title: string, startedAt: number, endedAt: number | null, endReason: string | null, promptCount: bigint, tokenCount: bigint | null, eventCount: bigint, status: SessionStatus, parserVersion: string | null, strategyVersion: string | null, 
/**
 * §G.2 defaults to `{}`. Do not store plaintext secrets or sensitive user data.
 */
metadataJson: string, createdAt: number, updatedAt: number, };
