// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 实际写入 app_settings 的字段类型 · 替代原 `Vec<String>` 中硬编码字段名
 *
 * 改前：`applied = vec!["font_family", "default_shell"]` · 前端 switch string · 易拼错
 * 改后：`applied = vec![AppliedField::FontFamily, AppliedField::DefaultShell]`
 * · ts-rs 自动生成 union literal · 前端 exhaustive match · 编译期保证
 */
export type AppliedField = "fontFamily" | "fontSize" | "theme" | "defaultShell" | "importedKeybindings";
