// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { theme: string, fontFamily: string, fontSize: number, defaultShell: string, pasteProtection: boolean, telemetryOptIn: boolean | null, gitUserName: string | null, gitUserEmail: string | null, bgOpacity: number, bgBlur: number, windowPaddingX: number, windowPaddingY: number, cursorStyle: string, cursorBlink: boolean, unfocusedPaneOpacity: number, 
/**
 * MVP-20 · 是否启用 PTY 预热池（新 tab 启动加速）
 */
ptyPoolEnabled: boolean, 
/**
 * MVP-20 · PTY 预热池容量（推荐 1-3 · 实际取值由 UI 限制）
 */
ptyPoolSize: number, };
