// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { theme: string, fontFamily: string, fontSize: number, defaultShell: string, pasteProtection: boolean, telemetryOptIn: boolean | null, gitUserName: string | null, gitUserEmail: string | null, bgOpacity: number, bgBlur: number, windowPaddingX: number, windowPaddingY: number, cursorStyle: string, cursorBlink: boolean, unfocusedPaneOpacity: number, };
