// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { language: string, theme: string, 
/**
 * 界面 UI 字体（写入 CSS `--font-ui` · 侧边栏 / 设置 / 按钮等）
 */
uiFontFamily: string, 
/**
 * 终端等宽字体（xterm + CSS `--font-mono`）
 */
fontFamily: string, fontSize: number, defaultShell: string, pasteProtection: boolean, telemetryOptIn: boolean | null, gitUserName: string | null, gitUserEmail: string | null, bgOpacity: number, bgBlur: number, windowPaddingX: number, windowPaddingY: number, cursorStyle: string, cursorBlink: boolean, unfocusedPaneOpacity: number, 
/**
 * MVP-20 · 是否启用 PTY 预热池（新 tab 启动加速）
 */
ptyPoolEnabled: boolean, 
/**
 * MVP-20 · PTY 预热池容量（推荐 1-3 · 实际取值由 UI 限制）
 */
ptyPoolSize: number, 
/**
 * 全局 sidebar 宽度（像素）· 跨 workspace 共享 · 类似 VSCode/Cursor 设计 ·
 * 区别于 per-workspace LayoutState 的 open/close。
 */
primaryWidth: number, secondaryWidth: number, bottomHeight: number, 
/**
 * MVP-17 · 用户选择的默认外部终端 ID · None = 每次问
 */
externalTermPreferred: string | null, 
/**
 * MVP-17 · "Don't ask again" 状态 · true 时跳过 PopToExternalDialog
 */
externalTermDontAskAgain: boolean, };
