// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 应用版本信息（用于 Privacy 面板调试展示 + crash payload 数据源）
 */
export type AppVersionInfo = { version: string, osType: string, buildTarget: string, };
