// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";

export type AuthRequest = { workspaceId: string, authChallengeId: string, taskId: string, remoteUrl: string, allowedMethods: Array<string>, method: AuthMethod, expiresAt: number, };
