// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthChallenge = { workspaceId: string, authChallengeId: string, taskId: string, remoteUrl: string, hostFingerprint: string | null, allowedMethods: Array<string>, expiresAt: number, };
