// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthMethod = { "kind": "sshAgent" } | { "kind": "sshKeyFile", path: string, passphrase: string | null, } | { "kind": "httpsHelper" } | { "kind": "httpsManual", username: string, password: string, };
