// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo } from "./BranchInfo";

export type BranchListResponse = { branches: Array<BranchInfo>, headName: string | null, detached: boolean, };
