// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchKind } from "./BranchKind";

export type BranchInfo = { name: string, fullRef: string, kind: BranchKind, upstream: string | null, ahead: number, behind: number, headCommit: string | null, };
