// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CherryPickStatus = { inProgress: boolean, currentIndex: number, totalCommits: number, conflictingFiles: Array<string>, };
