// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitError = { "kind": "noStagedFiles" } | { "kind": "identityMissing" } | { "kind": "hookFailed", stderr: string, exit_code: number, } | { "kind": "detachedHead" } | { "kind": "git2Error", message: string, };
