// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitAuthor } from "./CommitAuthor";
import type { CommitParent } from "./CommitParent";
import type { FileChange } from "./FileChange";

export type CommitDetail = { fullSha: string, shortSha: string, author: CommitAuthor, committer: CommitAuthor, message: string, parents: Array<CommitParent>, files: Array<FileChange>, };
