// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitAuthor } from "./CommitAuthor";

export type CommitResponse = { sha: string, shortSha: string, message: string, author: CommitAuthor, timestamp: number, };
