// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ConflictResolution = { "kind": "acceptOurs" } | { "kind": "acceptTheirs" } | { "kind": "acceptBoth" } | { "kind": "manual", content: string, };
