// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictHunkResolution } from "./ConflictHunkResolution";

export type ConflictResolveFileRequest = { workspaceId: string, filePath: string, resolutions: Array<ConflictHunkResolution>, };
