// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConflictHunk } from "./ConflictHunk";

export type ConflictedFile = { path: string, hunks: Array<ConflictHunk>, resolved: boolean, };
