// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Crash report 上报 payload · §G.2 锁定 3 字段（白名单防御）
 *
 * # 隐私约束（ADR-015 D1）
 *
 * 不含 IP / 用户路径 / commit 信息 / 终端内容 / 仓库名。
 * 不含原始 panic 字符串（用 SHA-256 哈希替代 · 不可逆）。
 * 字段白名单由本 struct 定义 + ts-rs 强制 + §C.3.1 unit test 守门。
 */
export type CrashReportPayload = { version: string, osType: string, stackTraceHash: string, };
