// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CrashRecoveryState = { inProgress: boolean, operation: string | null, branch: string | null, currentStep: number, totalSteps: number, };
