// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detached window 几何（创建时初始 bounds · 用户拖动后不更新到本结构）。
 */
export type DetachedWindowBounds = { x: number, y: number, width: number, height: number, };
