// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffLine } from "./DiffLine";

export type DiffHunk = { oldStart: number, newStart: number, lines: Array<DiffLine>, };
