// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiffHunk } from "./DiffHunk";

export type DiffResponse = { hunks: Array<DiffHunk>, binary: boolean, truncated: boolean, truncatedReason: string | null, oldSizeBytes: number | null, newSizeBytes: number | null, lineCount: number | null, };
