// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnvEntry } from "./EnvEntry";

export type EnvPreview = { visibleEntries: Array<EnvEntry>, filteredCount: number, };
