// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FetchProgressEvent = { workspaceId: string, taskId: string, stage: string, receivedObjects: number, totalObjects: number, receivedBytes: number, };
