// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo } from "./BranchInfo";

export type FetchResult = { fetchedRefs: Array<string>, prunedRefs: Array<string>, branches: Array<BranchInfo>, };
