// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";

export type FetchRequest = { workspaceId: string, remote: string, prune: boolean, authMethod: AuthMethod | null, taskId: string | null, };
