// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GitLogEntry = { shortSha: string, message: string, authorName: string, authoredDate: number, relativeTime: string, branchLabels: Array<string>, tagLabels: Array<string>, };
