// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitLogEntry } from "./GitLogEntry";

export type GitLogQueryResponse = { entries: Array<GitLogEntry>, hasMore: boolean, };
