// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitStatusGroup } from "./GitStatusGroup";

export type GitStatusCollapseRequest = { workspaceId: string, group: GitStatusGroup, collapsed: boolean, };
