// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileChange } from "./FileChange";

export type GitStatusResponse = { staged: Array<FileChange>, unstaged: Array<FileChange>, untracked: Array<FileChange>, };
