// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 导入字段类型 · spec §G.2 tagged union
 *
 * JSON serialization 形如：`{"kind":"fontFamily","value":"JetBrains Mono"}`
 */
export type ImportFieldType = { "kind": "fontFamily", value: string, } | { "kind": "fontSize", value: number, } | { "kind": "theme", value: string, } | { "kind": "shell", value: string, } | { "kind": "keyBinding", key: string, action: string, } | { "kind": "ansiColor", index: number, hex: string, };
