// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFieldType } from "./ImportFieldType";
import type { KeyBindingConflict } from "./KeyBindingConflict";

/**
 * 应用导入的请求（spec §G.1 · UI Step 3 提交）
 *
 * 用户从预览列表勾选要写入 app_settings 的字段
 *
 * Issue #206 Advisory #2 修复：删除 source 字段 · apply 函数从未引用 · 字段冗余
 * · 字段实际数据全在 fields 里 · UI 端 source 用于 step 状态 ≠ apply IPC 负载
 */
export type ImportApplyRequest = { 
/**
 * 勾选生效的字段集合
 */
fields: Array<ImportFieldType>, 
/**
 * 用户对每个冲突的决策（user_choice 已填）
 */
conflictResolutions: Array<KeyBindingConflict>, };
