// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 导入源枚举（spec §G.2）· 既给 Phase A parser 内部用 · 也是 IPC 类型
 *
 * JSON serialization：`"ghostty" | "iTerm2" | "alacritty"`（serde camelCase enum）
 */
export type ImportSource = "ghostty" | "iTerm2" | "alacritty";
