// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFieldType } from "./ImportFieldType";
import type { ImportSource } from "./ImportSource";
import type { KeyBindingConflict } from "./KeyBindingConflict";

/**
 * 应用导入的请求（spec §G.1 · UI Step 3 提交）
 *
 * 用户从预览列表勾选要写入 app_settings 的字段
 */
export type ImportApplyRequest = { 
/**
 * 用户选定的来源（标识用 · 实际数据在 fields）
 */
source: ImportSource, 
/**
 * 勾选生效的字段集合
 */
fields: Array<ImportFieldType>, 
/**
 * 用户对每个冲突的决策（user_choice 已填）
 */
conflictResolutions: Array<KeyBindingConflict>, };
