// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBindingConflict } from "./KeyBindingConflict";

/**
 * 应用结果（spec §G.1 · 写入 app_settings 的反馈）
 */
export type ImportApplyResult = { 
/**
 * 实际写入 app_settings 的字段名列表（如 `font_family` · `font_size` · `theme` · `default_shell` · `imported_keybindings`）
 */
applied: Array<string>, 
/**
 * 跳过的冲突（user_choice == KeepVibe 的）
 */
skippedConflicts: Array<KeyBindingConflict>, 
/**
 * 字段级错误（不阻止整体 · graceful）
 */
errors: Array<string>, };
