// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportScanResult } from "./ImportScanResult";
import type { KeyBindingConflict } from "./KeyBindingConflict";

/**
 * 跨源合并的预览（spec §G.1 · UI Step 2 数据）
 *
 * 同一 field type 多源命中时 · 用户最终勾选生效
 */
export type ImportPreview = { 
/**
 * 所有扫描的源（含未检测到 · 但保留以便 UI 全展示）
 */
sources: Array<ImportScanResult>, 
/**
 * 内置冲突（已 canonical 化）
 */
conflicts: Array<KeyBindingConflict>, };
