// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImportFieldType } from "./ImportFieldType";
import type { ImportSource } from "./ImportSource";

/**
 * 单源扫描结果 · spec §G.1
 *
 * 不暴露内部 `path: PathBuf`（仅 [`super::RawScanResult`] 有）·
 * 改用 `path_display` 字符串方便 UI 显示（仅展示 · 不参与逻辑）
 */
export type ImportScanResult = { source: ImportSource, pathExists: boolean, 
/**
 * 找到的实际配置文件路径（用于 UI 显示 · `~/...` 形式 · None 若未找到）
 */
pathDisplay: string | null, detectedFields: Array<ImportFieldType>, errors: Array<string>, };
