// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppliedField } from "./AppliedField";
import type { KeyBindingConflict } from "./KeyBindingConflict";

/**
 * 应用结果（spec §G.1 · 写入 app_settings 的反馈）
 */
export type ImportApplyResult = { 
/**
 * 实际写入 app_settings 的字段（Issue #206 Advisory #7 · 由 `Vec<String>` 改为 enum vec）
 */
applied: Array<AppliedField>, 
/**
 * 跳过的冲突（user_choice == KeepVibe 的）
 */
skippedConflicts: Array<KeyBindingConflict>, 
/**
 * 字段级错误（不阻止整体 · graceful）
 */
errors: Array<string>, };
