// Generated by crates/app/build.rs from ts-rs derives in vibestation-core.
// Do NOT edit manually. Run `cargo build` to regenerate.
// Source of truth: crates/core/src/workspace.rs · layout.rs · tabs.rs · pty.rs (SPIKE-08 §A rollout).
export type { WorkspaceMetadata } from "./WorkspaceMetadata";
export type { LayoutState } from "./LayoutState";
export type { TabState } from "./TabState";
export type { TabCreateRequest } from "./TabCreateRequest";
export type { TabCloseRequest } from "./TabCloseRequest";
export type { TabRenameRequest } from "./TabRenameRequest";
export type { TabListResponse } from "./TabListResponse";
export type { PtyStdoutEvent } from "./PtyStdoutEvent";
export type { PtyExitedEvent } from "./PtyExitedEvent";
export type { PtySpawnRequest } from "./PtySpawnRequest";
