// Generated by crates/app/build.rs from ts-rs derives in vibestation-core.
// Do NOT edit manually. Run `cargo build` to regenerate.
// Source of truth: crates/core/src/workspace.rs · layout.rs (SPIKE-08 §A rollout).
export type { WorkspaceMetadata } from "./WorkspaceMetadata";
export type { LayoutState } from "./LayoutState";
