// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBindingResolution } from "./KeyBindingResolution";

export type KeyBindingConflict = { 
/**
 * canonical form · 例 "Cmd+T"
 */
vibeKey: string, 
/**
 * canonical form · 同 vibe_key
 */
sourceKey: string, 
/**
 * 例 "tabs.create"（Vibestation 内置 action）
 */
vibeAction: string, 
/**
 * 例 "new_tab"（原终端 action 名）
 */
sourceAction: string, 
/**
 * 用户决策（默认 KeepVibe · UI 可改 Override）
 */
userChoice: KeyBindingResolution, };
