// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * v0.2 Smart Layout 预设种类 · ts-rs 新 binding。
 *
 * 保留旧 [`SmartLayoutKind`] 作为内部兼容类型 · 提供 `From` 转换。
 */
export type LayoutPresetKind = "solo" | "aiAndRunner" | "dualAi" | "tripleReview" | "quad";
