// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneListResponse } from "./PaneListResponse";

export type LayoutApplyResult = { response: PaneListResponse, reusedPaneIds: Array<string>, createdPaneIds: Array<string>, closedPaneIds: Array<string>, };
