// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutPresetKind } from "./LayoutPresetKind";

export type LayoutHistoryEntry = { preset: LayoutPresetKind, timestamp: number, paneCount: number, };
