// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";

/**
 * LayoutNode v1 envelope · 顶层版本化容器。
 *
 * 旧 `{"kind":"single","paneId":"p"}` 通过 [`LayoutEnvelope::from_legacy_node`]
 * 包装为 v1 envelope；序列化时输出包含 `version: 1` 的完整 JSON。
 */
export type LayoutEnvelope = { version: number, root: LayoutNode, focusedPaneId: string | null, updatedAt: number, };
