// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitDir } from "./SplitDir";

export type LayoutNode = { "kind": "single", paneId: string, } | { "kind": "split", direction: SplitDir, ratio: number, first: LayoutNode, second: LayoutNode, };
