// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tool Windows 布局状态 · IPC contract source of truth（详见 WorkspaceMetadata doc）。
 */
export type LayoutState = { primaryOpen: boolean, secondaryOpen: boolean, bottomOpen: boolean, primaryWidth: number, secondaryWidth: number, bottomHeight: number, };
