// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §G.3 `session_commit_links.link_state`.
 */
export type LinkState = "pending" | "confirmedAuto" | "confirmedManual" | "unlinked" | "superseded" | "stale";
