// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeStrategy } from "./MergeStrategy";

export type MergeRequest = { workspaceId: string, sourceBranch: string, strategy: MergeStrategy, commitMessage: string | null, };
