// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkOpError } from "./NetworkOpError";

export type OperationDoneEvent = { workspaceId: string, taskId: string, operation: string, outcome: string, error: NetworkOpError | null, };
