// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneFailureFallbackMode } from "./PaneFailureFallbackMode";
import type { ParsedIssue } from "./ParsedIssue";

export type PaneBuildFailedEvent = { workspaceId: string, linkId: string, parentPaneId: string, childPaneId: string, commandRunId: string, exitCode: number | null, rawExcerpt: string, parsedIssues: Array<ParsedIssue>, parserConfidence: number, fallbackMode: PaneFailureFallbackMode, occurredAt: number, truncatedCount: number, redactionCount: number, };
