// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §K.1 `PaneUnlinkResult`。
 */
export type PaneUnlinkResult = { linkId: string, 
/**
 * 首次软删 true · 本就不存在 / 已删 false（幂等）。
 */
removed: boolean, };
