// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `pane_detach_close` IPC 返回 · 标识被重新 attach 的 pane。
 */
export type PaneDetachCloseResult = { paneId: string, };
