// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §K.2 `PaneTriggerEvent` · §K.6 例。被订阅 child Pane 失败触发源记录。
 */
export type PaneTriggerEvent = { workspaceId: string, childPaneId: string, commandRunId: string, 
/**
 * §C.55：`exitCode` / `signal` / `watchRerun` / `manualRerun`。
 */
reason: string, exitCode: number | null, command: string, occurredAt: number, };
