// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §G.1 `link_kind` · §K.3 binding 2。首版仅 `failureFeedback`（未来 kind 需 migration）。
 */
export type PaneLinkKind = "failureFeedback";
