// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";

export type PaneMaximizeResult = { maximized: boolean, restoredLayout: LayoutNode | null, restoredFocusedPaneId: string | null, };
