// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutNode } from "./LayoutNode";
import type { PaneState } from "./PaneState";

export type PaneListResponse = { panes: Array<PaneState>, layout: LayoutNode, focusedPaneId: string | null, };
