// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §K.5 `PaneLinkError` · UI-facing binding 18。tagged enum：machine 可读 `kind` +
 * 人类可读 message（thiserror `Display`）。serde adjacently-tagged → JSON
 * `{ "kind": "...", "detail"?: "..." }`。
 */
export type PaneLinkError = { "kind": "crossWorkspaceDenied" } | { "kind": "invalidParentPaneType" } | { "kind": "invalidChildPaneType" } | { "kind": "paneNotFound", "detail": string } | { "kind": "linkNotFound", "detail": string } | { "kind": "parserUnavailable", "detail": string } | { "kind": "parserTimeout", "detail": string } | { "kind": "promptSanitizationFailed", "detail": string } | { "kind": "dbError", "detail": string } | { "kind": "unsupportedCliKind", "detail": string };
