// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneDetachAction } from "./PaneDetachAction";

/**
 * `pane_detach_state_changed` 事件 payload。
 */
export type PaneDetachStateEvent = { paneId: string, action: PaneDetachAction, 
/**
 * detach 时为 `Some(label)` · attach 时为 `None`。
 */
windowLabel: string | null, };
