// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitDir } from "./SplitDir";

export type PaneResizeStepRequest = { tabId: string, paneId: string, direction: SplitDir, stepRatio: number, };
