// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneLinkKind } from "./PaneLinkKind";
import type { PaneLinkStatus } from "./PaneLinkStatus";

/**
 * §K.2 `PaneLinkedEvent` · §K.6 例。link created/enabled/disabled/stale/removed。
 */
export type PaneLinkedEvent = { workspaceId: string, linkId: string, parentPaneId: string, childPaneId: string, linkKind: PaneLinkKind, status: PaneLinkStatus, updatedAt: number, };
