// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaneState = { paneId: string, tabId: string, shell: string, cwd: string, createdAt: number, };
