// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §K.1 `PaneUnlinkRequest`。
 */
export type PaneUnlinkRequest = { workspaceId: string, linkId: string, };
