// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetachedWindowBounds } from "./DetachedWindowBounds";

/**
 * `pane_detach_open` IPC 返回。
 */
export type PaneDetachOpenResult = { windowLabel: string, initialBounds: DetachedWindowBounds, };
