// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneFailureFallbackMode } from "./PaneFailureFallbackMode";
import type { ParsedIssue } from "./ParsedIssue";

export type PaneFailurePreviewResult = { promptFragment: string, rawExcerpt: string, parsedIssues: Array<ParsedIssue>, parserConfidence: number, fallbackMode: PaneFailureFallbackMode, truncatedCount: number, redactionCount: number, };
