// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `pane_detach_open` IPC 入参。
 */
export type PaneDetachOpenRequest = { paneId: string, };
