// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §K.6 `status` · §K.3 binding 3。link 生命周期状态。
 */
export type PaneLinkStatus = "enabled" | "disabled" | "stale" | "removed";
