// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneNavDirection } from "./PaneNavDirection";

export type PaneNavigateRequest = { tabId: string, fromPaneId: string, direction: PaneNavDirection, };
