// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneLink } from "./PaneLink";

/**
 * §K.1 `PaneLinkResult` · `pane:link` / `set_enabled` 响应。
 */
export type PaneLinkResult = { link: PaneLink, 
/**
 * §E B.4：命中已有 link 返回 true（幂等）· 新建 false。
 */
alreadyExisted: boolean, };
