// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SplitDir } from "./SplitDir";

export type PaneCreateRequest = { tabId: string, parentPaneId: string, direction: SplitDir, shell: string, };
