// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 为 tab 初始化第一个 Pane（layout 为 `Single { paneId: "" }` 时调用 · idempotent）。
 *
 * 触发场景：MVP-04 创建 tab 时 layout 默认为空 paneId · MVP-05 Phase C 前端在第一次激活 tab
 * 时调用此命令 · 把 tab 切换到 Pane 模式（创建一个 Pane row + 改 layout 为指向 Pane 的 Single
 * + 设置 focused_pane_id）。
 *
 * 若 tab 已有 Pane（layout.paneId 非空 + panes 表有对应行）· 返回当前 PaneListResponse · 不重复创建。
 */
export type PaneInitRequest = { tabId: string, shell: string, cwd: string, };
