// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §K.1 `PaneLinkSetEnabledRequest` · §C 临时暂停/恢复（不删关系）。
 */
export type PaneLinkSetEnabledRequest = { workspaceId: string, linkId: string, enabled: boolean, };
