// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetachedWindowBounds } from "./DetachedWindowBounds";

/**
 * `pane_detach_list` IPC 返回的单项。
 */
export type PaneDetachListEntry = { paneId: string, windowLabel: string, bounds: DetachedWindowBounds, };
