// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneLinkKind } from "./PaneLinkKind";

/**
 * §K.4 `PaneLinkRequest` · `pane:link` 命令请求。
 */
export type PaneLinkRequest = { workspaceId: string, parentPaneId: string, childPaneId: string, linkKind: PaneLinkKind, };
