// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneLinkKind } from "./PaneLinkKind";

/**
 * §K.3 binding 1 · §G schema 行映射。仅 metadata（spec §G.3：不存 raw/prompt/token）。
 */
export type PaneLink = { id: string, workspaceId: string, parentPaneId: string, childPaneId: string, linkKind: PaneLinkKind, enabled: boolean, 
/**
 * §G.1 `'structured' | 'rawText' | 'disabledByParser'`。
 */
fallbackMode: string, 
/**
 * §G.1 `'user' | 'preset' | 'migration'`；MVP-18 用 `user`。
 */
createdBy: string, createdAt: number, updatedAt: number, lastTriggeredAt: number, };
