// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaneLinkError } from "./PaneLinkError";

/**
 * §K.2 `PaneLinkErrorEvent` · recoverable create/unlink/trigger 错误通知前端。
 */
export type PaneLinkErrorEvent = { workspaceId: string, error: PaneLinkError, };
