// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedIssue } from "./ParsedIssue";

export type PaneFailurePreviewRequest = { workspaceId: string, childPaneId: string, commandRunId: string, exitCode: number | null, command: string, cwd: string, cliKind: string, rawOutput: string, parsedIssues: Array<ParsedIssue>, };
