// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedIssueSeverity } from "./ParsedIssueSeverity";

export type ParsedIssue = { severity: ParsedIssueSeverity, file: string | null, line: number | null, column: number | null, message: string, };
