// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";
import type { GitStatusResponse } from "./GitStatusResponse";
import type { PullStrategy } from "./PullStrategy";

export type PullRequest = { workspaceId: string, remote: string, branch: string, strategy: PullStrategy, frontendStatusSnapshot: GitStatusResponse | null, frontendStatusTakenAt: bigint | null, authMethod: AuthMethod | null, taskId: string | null, };
