// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PushProgressEvent = { workspaceId: string, taskId: string, stage: string, objectsTotal: number, objectsDone: number, bytesTotal: number, bytesDone: number, };
