// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AuthMethod } from "./AuthMethod";

export type PushRequest = { workspaceId: string, remote: string, branch: string, force: boolean, expectedRemoteOid: string | null, authMethod: AuthMethod | null, taskId: string | null, };
