// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Branch 变化事件（git:branch-changed 联动 · refs_hash 用于失效判断）
 */
export type RailGraphBranchChangedPayload = { workspaceId: string, headOid: string | null, refsHash: string, branchCount: number, };
