// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rebase 状态同步（MVP-16 overlay 联动 · phase D emit）
 */
export type RailGraphRebaseStatePayload = { workspaceId: string, 
/**
 * "in_progress" | "done" | "aborted"
 */
state: string, };
