// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Rail graph 视口同步事件（前端滚动时触发 · phase D emit）
 */
export type RailGraphViewportSyncPayload = { workspaceId: string, scrollTop: number, rowHeight: number, viewportStart: number, viewportEnd: number, };
