// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 性能采样（phase D perf budget 验收）
 */
export type RailGraphPerfSample = { workspaceId: string, 
/**
 * "firstPaint" | "scroll" | "hover" | "branchChanged"
 */
phase: string, durationMs: number, commitCount: number, branchCount: number, };
