// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebaseInteractiveStep } from "./RebaseInteractiveStep";

export type RebaseInteractivePlan = { steps: Array<RebaseInteractiveStep>, };
