// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RebaseStartRequest = { workspaceId: string, branch: string, onto: string, interactive: boolean, };
