// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RebaseOp } from "./RebaseOp";

export type RebaseInteractiveStep = { stepId: string, op: RebaseOp, commitSha: string, messageOverride: string | null, };
