// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RevertPlanEntry } from "./RevertPlanEntry";

/**
 * `build_revert_plan` 输出（spec §B.2 过滤 + §J R4 排序后的最终计划）。
 */
export type RevertPlan = { sessionId: string, 
/**
 * newest-first（commit_timestamp 降序）· 已过滤 unlinked/superseded/stale。
 */
entries: Array<RevertPlanEntry>, 
/**
 * 任一 entry low_confidence → true（UI 顶部 ⚠ 警告 · spec §D.2）。
 */
hasLowConfidence: boolean, };
