// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * revert plan 里的单条目（spec §K `RollbackCommitEntry` 的 plan 阶段子集 ·
 * message/author/files_changed 等展示字段 M2 preview IPC 时 git2 enrich）。
 */
export type RevertPlanEntry = { sha: string, confidence: number, 
/**
 * 默认 include = 高置信（≥ 0.9）或已确认绑定；低置信 pending 默认 false。
 */
include: boolean, 
/**
 * confidence < 0.9 → UI 高亮警告（spec §C.Do.3 · §D.2 ⚠ 标记）。
 */
lowConfidence: boolean, 
/**
 * commit timestamp（epoch 秒 · 跨 IPC 用 number 防 bigint · 既有约定）。
 */
commitTimestamp: number, };
