// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `rollback:*` 状态机的类型化 status（spec §K · status union 保真）。
 *
 * serde `snake_case` 同时充当两个契约的 single source of truth：
 * 1. DB `rollback_ops.status` 的 TEXT 持久值（与既有 SQL 字面量
 *    `'in_progress'` / `'conflict_paused'` 等完全一致 · round-trip 单测守护）；
 * 2. ts-rs 生成的 TS union literal
 *    `"idle" | "in_progress" | "conflict_paused" | "completed" | "aborted"`
 *    （spec §K 契约 · 替换 Phase A/B/C 的裸 `string`）。
 *
 * 用 enum 而非 `&str` 常量：abort / resume / crash-recovery 的状态转换在
 * 编译期穷尽匹配（Rust 状态机模式 · illegal states unrepresentable）·
 * 并让 `SessionDetailView.tsx` 此前的 `status:"starting"` 越界值在
 * 跨 IPC 边界即类型错误。
 */
export type RollbackStatusKind = "idle" | "in_progress" | "conflict_paused" | "completed" | "aborted";
