// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `rollback:execute` progress payload（spec §G.3 / §G.4）。
 */
export type RollbackProgress = { done: number, total: number, currentSha: string | null, status: string, };
