// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RollbackCommitEntry } from "./RollbackCommitEntry";

/**
 * `rollback:preview` 返回类型（spec §K）。
 */
export type RollbackPreview = { sessionId: string, commits: Array<RollbackCommitEntry>, totalFilesChanged: number, totalInsertions: number, totalDeletions: number, hasLowConfidence: boolean, };
