// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `rollback:*` 操作的统一错误（spec §G.3 `RollbackError` · §I 起点 A7：
 * 仿 MVP-09 `CommitError` / MVP-16 `RebaseOpError` 结构化变体）。
 *
 * M1 只构建 plan，实际触发的是 `EmptyPlan` / `SessionNotFound`；其余变体
 * 是 M2（revert 序列 / IPC）的契约前置声明（spec A7 要求 enum 完整 ·
 * enum 全列变体是契约定义，非投机代码）。
 */
export type RollbackError = { "kind": "dirtyWorkingTree", modified: Array<string>, staged: Array<string>, } | { "kind": "conflictDetected", commit_sha: string, files: Array<string>, } | { "kind": "sessionNotFound", session_id: string, } | { "kind": "emptyPlan", session_id: string, } | { "kind": "inProgress", session_id: string, } | { "kind": "git2Error", class: string, code: number, message: string, } | { "kind": "dbError", message: string, };
