// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RollbackStatusKind } from "./RollbackStatusKind";

/**
 * app 启动 crash recovery 检测的单条结果（spec §H.9 · §I Phase D ·
 * `git:rollback-crash-recovery-detected` event payload）。
 *
 * 与 `RollbackStatus` 区别：携带 `workspace_id`（前端按 workspace 路由 +
 * 渲染全局 recovery banner）。镜像 MVP-16 `RebaseCrashRecoveryEvent` 模式 ·
 * 但 rollback 是 session 维度（session_id / current_idx / total）· 故平行
 * 独立类型而非塞进 rebase 的 workspace 维度 payload（保真 · §B.4）。
 */
export type RollbackCrashRecovery = { workspaceId: string, sessionId: string, status: RollbackStatusKind, currentIdx: number, total: number, currentSha: string | null, };
