// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RollbackStatusKind } from "./RollbackStatusKind";

/**
 * `rollback:status` 返回类型（spec §K）。
 */
export type RollbackStatus = { sessionId: string, status: RollbackStatusKind, currentIdx: number, total: number, currentSha: string | null, };
