// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `rollback:preview` 单 commit 展示项（spec §K）。
 */
export type RollbackCommitEntry = { sha: string, message: string, author: string, timestamp: number, confidence: number, include: boolean, filesChanged: number, };
