// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `rollback:abort` 返回类型（spec §G.3）。
 */
export type RollbackAbortResult = { success: boolean, headSha: string, error: string | null, };
