// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:commit-unbound` · commit 完成解绑（徽章变 stale/移除 · §D.2）。
 */
export type SessionCommitUnboundEvent = { workspaceId: string, linkId: string, commitSha: string, };
