// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionError } from "./SessionError";

/**
 * `session:error` · 可恢复错误通知前端（§K.2 · 复用 canonical
 * `SessionError` tagged enum · 不另造错误形状）。
 */
export type SessionErrorEvent = { workspaceId: string, error: SessionError, };
