// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSession } from "./AiSession";

/**
 * `session:list` 响应 · `started_at DESC`（最新优先 · §G.2 索引）。
 */
export type SessionListResult = { sessions: Array<AiSession>, };
