// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSession } from "./AiSession";

/**
 * `session:end` 响应 · 返回结束后的 session 行。
 */
export type SessionEndResult = { session: AiSession, };
