// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §K.4 `SessionBindCommitRequest.mode` · 自动推断 vs 用户手动指派。
 */
export type SessionBindMode = "auto" | "manual";
