// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:rebind` · 改绑 commit 到同 workspace 另一 session（§E5.4/§E5.5）。
 */
export type SessionRebindRequest = { workspaceId: string, linkId: string, targetSessionId: string, reason: string | null, };
