// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSession } from "./AiSession";

/**
 * `session:started` · session 启动通知（前端刷新列表 / 徽章 pending 点）。
 */
export type SessionStartedEvent = { workspaceId: string, session: AiSession, };
