// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:end` · 结束 session，写 `end_reason`（§G.2 status 流转）。
 */
export type SessionEndRequest = { workspaceId: string, sessionId: string, 
/**
 * `manual_end` | `idle_cutoff` | `process_exit` | `clear` …（§C.1.1）。
 */
endReason: string | null, };
