// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSession } from "./AiSession";
import type { SessionCommitLink } from "./SessionCommitLink";

/**
 * `session:get-detail` 响应 · session 主体 + 关联 commit links + 基础统计
 * （§D.1 Summary strip：commit 数 / 置信均值）。
 */
export type SessionDetailResult = { session: AiSession, links: Array<SessionCommitLink>, 
/**
 * 关联 commit 数（= 未软删 links 计数 · §D.1 Summary）。
 */
commitCount: number, 
/**
 * 置信均值（无 link 时 0.0 · §D.1 Summary "绑定置信均值"）。
 */
avgConfidence: number, };
