// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:start` · 显式或自动开启 session（§C.1.1 boundary）。
 */
export type SessionStartRequest = { workspaceId: string, cliKind: string, 
/**
 * `auto`（进程驱动）| `manual`（用户驱动）· §G.2 `source`。
 */
source: string, 
/**
 * 触发 session 的 pane（边界识别上下文 · 可空 = 非 pane 驱动）。
 */
paneId: string | null, title: string | null, 
/**
 * 起始时刻 epoch millis（前端不传时 handler 取 now · §K.4 风格）。
 */
startedAt: number | null, };
