// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §G.2 `ai_sessions.status`.
 */
export type SessionStatus = "active" | "ended" | "idleCutoff" | "archived";
