// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionBindMode } from "./SessionBindMode";

/**
 * §K.4 `SessionBindCommitRequest` verbatim · 自动/手动绑定 commit。
 */
export type SessionBindCommitRequest = { workspaceId: string, commitSha: string, 
/**
 * `None` = 让后端按策略推断候选 session；`Some` = 显式指派（manual）。
 */
sessionId: string | null, mode: SessionBindMode, reason: string | null, };
