// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionCommitLink } from "./SessionCommitLink";

/**
 * `session:commit-bound` · commit 完成绑定（Git Log 徽章异步刷新 · §D.2）。
 */
export type SessionCommitBoundEvent = { workspaceId: string, link: SessionCommitLink, };
