// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionCommitLink } from "./SessionCommitLink";

/**
 * `session:recalculate-candidates` 响应 · 返回该 commit 当前候选 link 集
 * （含 pending · 供 UI 让用户挑选确认）。
 */
export type SessionRecalcResult = { candidates: Array<SessionCommitLink>, };
