// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionCommitLink } from "./SessionCommitLink";

/**
 * `session:rebind` 响应 · 旧 link → superseded · 返回新建 link。
 */
export type SessionRebindResult = { supersededLinkId: string, newLink: SessionCommitLink, };
