// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:list` · 按 workspace 列 session（§D.1 列表视图）。
 */
export type SessionListRequest = { workspaceId: string, };
