// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AiSession } from "./AiSession";

/**
 * `session:start` 响应 · 返回新建（或复用 active）的 session 行。
 */
export type SessionStartResult = { session: AiSession, 
/**
 * true = 命中已有 active session（幂等 · 未新建）· false = 新建。
 */
alreadyActive: boolean, };
