// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionCommitLink } from "./SessionCommitLink";

/**
 * `session:link-updated` · pending → confirmed 等状态变更（徽章弱化样式
 * 切换 · §D.2 置信度样式）。
 */
export type SessionLinkUpdatedEvent = { workspaceId: string, link: SessionCommitLink, };
