// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:unbind` · 软解绑 + 审计（§H5 不硬删）。
 */
export type SessionUnbindRequest = { workspaceId: string, linkId: string, reason: string | null, };
