// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:get-detail` · 详情页数据（§D.1 Session 详情视图）。
 */
export type SessionDetailRequest = { workspaceId: string, sessionId: string, };
