// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:ended` · session 结束通知（含 end_reason · §D.1 状态切换）。
 */
export type SessionEndedEvent = { workspaceId: string, sessionId: string, endReason: string | null, };
