// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LinkState } from "./LinkState";

/**
 * §G.3 `session_commit_links` row mapping.
 */
export type SessionCommitLink = { id: string, workspaceId: string, sessionId: string, commitSha: string, 
/**
 * SQL INTEGER 0/1 maps at the DAO boundary; canonical Rust contract is bool.
 */
isPrimary: boolean, linkState: LinkState, autoBound: boolean, confidence: number, confidenceReason: string, strategyVersion: string, sourceEventId: string | null, linkedAt: number, unlinkedAt: number | null, unlinkedReason: string | null, supersededByLinkId: string | null, createdBy: string, reviewedBy: string | null, createdAt: number, updatedAt: number, };
