// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:unbind` 响应 · 幂等（首次软删 true · 已删/不存在 false）。
 */
export type SessionUnbindResult = { linkId: string, unlinked: boolean, };
