// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `session:recalculate-candidates` · 重算某 commit 的候选关联（§D.3
 * "Unbind and recalc" / §C.1.14 最小回填）。
 */
export type SessionRecalcRequest = { workspaceId: string, commitSha: string, };
