// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionCommitLink } from "./SessionCommitLink";

/**
 * `session:bind-commit` 响应 · 返回新建的 link（含置信度 / pending 状态）。
 */
export type SessionBindCommitResult = { link: SessionCommitLink, 
/**
 * §H4：低置信自动绑定落 `pending`（true = 待人工确认 · 不当 confirmed）。
 */
requiresConfirmation: boolean, };
