// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetGitIdentityRequest = { workspaceId: string, name: string, email: string, scope: string, };
