// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingsUpdateRequest = { language: string | null, theme: string | null, uiFontFamily: string | null, fontFamily: string | null, fontSize: number | null, defaultShell: string | null, pasteProtection: boolean | null, telemetryOptIn: boolean | null, gitUserName: string | null, gitUserEmail: string | null, bgOpacity: number | null, bgBlur: number | null, windowPaddingX: number | null, windowPaddingY: number | null, cursorStyle: string | null, cursorBlink: boolean | null, unfocusedPaneOpacity: number | null, ptyPoolEnabled: boolean | null, ptyPoolSize: number | null, primaryWidth: number | null, secondaryWidth: number | null, bottomHeight: number | null, 
/**
 * 外层 Some = 请求包含该字段 · 内层 None = 清空偏好（每次询问）
 */
externalTermPreferred: string | null | null, externalTermDontAskAgain: boolean | null, };
