// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 一条系统认证的 shell · 路径 + 显示用 label（basename）。
 */
export type ShellInfo = { path: string, label: string, };
