// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * MVP-20 BUG-001 修复 · IPC `tab_pty_spawn` / `pane_pty_spawn` 返回类型
 *
 * `warm: true` 表示 PTY 预热池命中 · 前端必须进入 ANSI clear filter 模式
 * 隐藏 cd 注入命令的 zsh ZLE echo + syntax-highlighting 重绘 flash
 * （root cause: zsh 把 stdin 注入当 user input · ZLE 必 echo · syntax-highlighting
 *  redraw 让命令行短暂可见 · clear 命令 fork 慢 ~50-100ms 用户能看到）
 *
 * 前端实现：见 `web/src/panels/Terminal/PaneTerminal.tsx` 的 ANSI clear filter
 */
export type SpawnResult = { 
/**
 * true = pool 命中（前端 buffer + ANSI clear filter）
 * false = cold spawn（前端正常 write）
 */
warm: boolean, };
