// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageFailedItem } from "./StageFailedItem";

export type StageResult = { stagedCount: number, failed: Array<StageFailedItem>, };
