// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo } from "./BranchInfo";

export type SwitcherMatch = { branch: BranchInfo, score: number, matchIndices: Array<number>, };
