// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for creating a new tab.
 */
export type TabCreateRequest = { workspaceId: string, name: string | null, shell: string | null, cwd: string | null, };
