// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for closing a tab.
 */
export type TabCloseRequest = { tabId: string, };
