// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TabState } from "./TabState";

/**
 * Response for listing tabs in a workspace.
 */
export type TabListResponse = { tabs: Array<TabState>, };
