// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for reordering a tab via drag-drop · MVP-20 follow-up。
 * `new_index` 是 0-based · workspace 内的目标位置。后端会重新分配该 workspace
 * 所有 tabs 的 position 让其连续递增（避免 gap 累积）。
 */
export type TabReorderRequest = { tabId: string, newIndex: number, };
