// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tab state · IPC contract source of truth (spec §G.2).
 *
 * `scroll_back` is intentionally excluded from this struct — it can be very
 * large (up to 10k lines) and would drag IPC performance. Frontend must use
 * `tab_scrollback_fetch` command to pull visible buffer on demand.
 */
export type TabState = { tabId: string, workspaceId: string, name: string, shell: string, cwd: string, createdAt: number, };
