// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Telemetry 状态（用于 settings 面板显示）
 */
export type TelemetryStatus = { 
/**
 * 当前 opt-in 决策 · `null` = 未决策（首次启动）
 */
optIn: boolean | null, 
/**
 * 收集端点描述（DSN 不暴露 · 仅显示自托管 / cloud 二选一）
 */
endpointHost: string, 
/**
 * 数据收集摘要（用于 Privacy 面板 "View what we collect"）
 */
dataCollectionSummary: string, 
/**
 * SDK 是否已初始化（仅 opt_in == true 且 DSN 存在时为 true）
 */
initialized: boolean, };
