// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Telemetry opt-in 决策请求（前端 → Rust）
 */
export type TelemetryOptInRequest = { optIn: boolean, };
