// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * vibestation 唯一支持的主题模式 · 类型层防御 + ts-rs 自动生成 union literal
 *
 * 之前是 `String`（runtime validation 在 apply round 1 修）· 但类型层仍宽
 * · parser 可能 detect "tokyo-night" 这种 ghostty palette name · 到 apply
 * 才 reject。改 enum 让 parser 层就 reject · 编译期保证只有 light/dark/auto
 * 能流到下游。
 */
export type ThemeMode = "light" | "dark" | "auto";
