// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workspace metadata · IPC contract source of truth.
 *
 * 前端类型由 ts-rs 自动生成到 `web/src/bindings/WorkspaceMetadata.ts`（见
 * `crates/app/build.rs`）· 禁止手写 TypeScript 对偶 interface · 避免 H2 类
 * camelCase / snake_case drift 事故（见 `docs/spikes/SPIKE-08-report.md §A`）。
 */
export type WorkspaceMetadata = { workspaceId: string, name: string, path: string, hasGit: boolean, repoRoot: string | null, 
/**
 * Unix timestamp (seconds)· 映射为 TS `number` 而非默认 `bigint`：unix 时间戳
 * 秒数在可预见未来（~year 285476）都 < 2^53 · 用 `number` 前端 Date/sort 零改动。
 */
createdAt: number, 
/**
 * 同 `created_at`。
 */
lastOpened: number, };
