// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LayoutEnvelope } from "./LayoutEnvelope";

export type WorkspaceLayoutState = { workspaceId: string, envelope: LayoutEnvelope | null, };
