//! Tauri build hook + ts-rs IPC contract codegen。
//!
//! 在每次 `cargo build` 时：
//! 1. 调 `tauri-build` 生成 Tauri config / capability schema
//! 2. 从 `vibestation-core` 导出 IPC struct 到
//!    `web/src/bindings/*.ts` · 供前端 `import` 消费
//!
//! 这是 SPIKE-08 §A（`docs/spikes/SPIKE-08-report.md`）的生产化落地 · 防止
//! MVP-02 H2 类 camelCase / snake_case drift 事故。

use std::{fs, path::PathBuf};

use ts_rs::{Config, TS};
use vibestation_core::{
    LayoutState, PtyExitedEvent, PtySpawnRequest, PtyStdoutEvent, TabCloseRequest,
    TabCreateRequest, TabListResponse, TabRenameRequest, TabState, WorkspaceMetadata,
};

fn main() {
    tauri_build::build();

    // 监控 core crate 的 IPC contract 源文件 · 改动时重跑 build.rs。
    println!("cargo:rerun-if-changed=../core/src/workspace.rs");
    println!("cargo:rerun-if-changed=../core/src/layout.rs");
    println!("cargo:rerun-if-changed=../core/src/tabs.rs");
    println!("cargo:rerun-if-changed=../core/src/pty.rs");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output_dir = manifest_dir.join("../../web/src/bindings");

    fs::create_dir_all(&output_dir).expect("create web/src/bindings");

    // ts-rs 12 · `Config::with_out_dir` 指定输出根目录 · `export_all` 递归
    // 导出 struct 及其间接引用的类型。
    let config = Config::new().with_out_dir(&output_dir);
    WorkspaceMetadata::export_all(&config).expect("export WorkspaceMetadata");
    LayoutState::export_all(&config).expect("export LayoutState");
    TabState::export_all(&config).expect("export TabState");
    TabCreateRequest::export_all(&config).expect("export TabCreateRequest");
    TabCloseRequest::export_all(&config).expect("export TabCloseRequest");
    TabRenameRequest::export_all(&config).expect("export TabRenameRequest");
    TabListResponse::export_all(&config).expect("export TabListResponse");
    PtyStdoutEvent::export_all(&config).expect("export PtyStdoutEvent");
    PtyExitedEvent::export_all(&config).expect("export PtyExitedEvent");
    PtySpawnRequest::export_all(&config).expect("export PtySpawnRequest");

    // 前端统一 import 入口（手工维护 · 防缺文件 · SPIKE-08 POC pattern）。
    fs::write(
        output_dir.join("index.ts"),
        [
            "// Generated by crates/app/build.rs from ts-rs derives in vibestation-core.",
            "// Do NOT edit manually. Run `cargo build` to regenerate.",
            "// Source of truth: crates/core/src/workspace.rs · layout.rs · tabs.rs · pty.rs (SPIKE-08 §A rollout).",
            "export type { WorkspaceMetadata } from \"./WorkspaceMetadata\";",
            "export type { LayoutState } from \"./LayoutState\";",
            "export type { TabState } from \"./TabState\";",
            "export type { TabCreateRequest } from \"./TabCreateRequest\";",
            "export type { TabCloseRequest } from \"./TabCloseRequest\";",
            "export type { TabRenameRequest } from \"./TabRenameRequest\";",
            "export type { TabListResponse } from \"./TabListResponse\";",
            "export type { PtyStdoutEvent } from \"./PtyStdoutEvent\";",
            "export type { PtyExitedEvent } from \"./PtyExitedEvent\";",
            "export type { PtySpawnRequest } from \"./PtySpawnRequest\";",
            "",
        ]
        .join("\n"),
    )
    .expect("write bindings index");
}
