//! Tauri build hook + ts-rs IPC contract codegen。
//!
//! 在每次 `cargo build` 时：
//! 1. 调 `tauri-build` 生成 Tauri config / capability schema
//! 2. 从 `vibestation-core` 导出 `WorkspaceMetadata` / `LayoutState` 到
//!    `web/src/bindings/*.ts` · 供前端 `import` 消费
//!
//! 这是 SPIKE-08 §A（`docs/spikes/SPIKE-08-report.md`）的生产化落地 · 防止
//! MVP-02 H2 类 camelCase / snake_case drift 事故。**禁止** 前端再手写
//! `WorkspaceMetadata` / `LayoutState` interface。

use std::{fs, path::PathBuf};

use ts_rs::{Config, TS};
use vibestation_core::{LayoutState, WorkspaceMetadata};

fn main() {
    tauri_build::build();

    // 监控 core crate 的 IPC contract 源文件 · 改动时重跑 build.rs。
    println!("cargo:rerun-if-changed=../core/src/workspace.rs");
    println!("cargo:rerun-if-changed=../core/src/layout.rs");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let output_dir = manifest_dir.join("../../web/src/bindings");

    fs::create_dir_all(&output_dir).expect("create web/src/bindings");

    // ts-rs 12 · `Config::with_out_dir` 指定输出根目录 · `export_all` 递归
    // 导出 struct 及其间接引用的类型（与 SPIKE-08 POC `build.rs` 同步）。
    let config = Config::new().with_out_dir(&output_dir);
    WorkspaceMetadata::export_all(&config).expect("export WorkspaceMetadata");
    LayoutState::export_all(&config).expect("export LayoutState");

    // 前端统一 import 入口（手工维护 · 防缺文件 · SPIKE-08 POC pattern）。
    fs::write(
        output_dir.join("index.ts"),
        [
            "// Generated by crates/app/build.rs from ts-rs derives in vibestation-core.",
            "// Do NOT edit manually. Run `cargo build` to regenerate.",
            "// Source of truth: crates/core/src/workspace.rs · layout.rs (SPIKE-08 §A rollout).",
            "export type { WorkspaceMetadata } from \"./WorkspaceMetadata\";",
            "export type { LayoutState } from \"./LayoutState\";",
            "",
        ]
        .join("\n"),
    )
    .expect("write bindings index");
}
