use std::{env, fs, path::PathBuf};

use ts_rs::{Config, TS};

#[path = "src/contract.rs"]
mod contract;

use contract::{
    DeleteWorkspaceRequest, DeleteWorkspaceResponse, WorkspaceDraft, WorkspaceListResponse,
    WorkspaceRecord,
};

fn main() {
    tauri_build::build();
    println!("cargo:rerun-if-changed=src/contract.rs");
    println!("cargo:rerun-if-changed=src/lib.rs");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let output_dir = manifest_dir.join("../src/bindings");

    fs::create_dir_all(&output_dir).expect("create bindings dir");

    let config = Config::new().with_out_dir(&output_dir);

    WorkspaceDraft::export(&config).expect("export WorkspaceDraft");
    WorkspaceRecord::export_all(&config).expect("export WorkspaceRecord");
    WorkspaceListResponse::export(&config).expect("export WorkspaceListResponse");
    DeleteWorkspaceRequest::export(&config).expect("export DeleteWorkspaceRequest");
    DeleteWorkspaceResponse::export(&config).expect("export DeleteWorkspaceResponse");

    fs::write(
        output_dir.join("index.ts"),
        [
            "// Generated by src-tauri/build.rs. Do not edit manually.",
            "export type { WorkspaceDraft } from \"./WorkspaceDraft\";",
            "export type { WorkspaceRecord } from \"./WorkspaceRecord\";",
            "export type { WorkspaceListResponse } from \"./WorkspaceListResponse\";",
            "export type { DeleteWorkspaceRequest } from \"./DeleteWorkspaceRequest\";",
            "export type { DeleteWorkspaceResponse } from \"./DeleteWorkspaceResponse\";",
            "",
        ]
        .join("\n"),
    )
    .expect("write bindings index");
}
