// Generated by src-tauri/build.rs. Do not edit manually.
export type { WorkspaceDraft } from "./WorkspaceDraft";
export type { WorkspaceRecord } from "./WorkspaceRecord";
export type { WorkspaceListResponse } from "./WorkspaceListResponse";
export type { DeleteWorkspaceRequest } from "./DeleteWorkspaceRequest";
export type { DeleteWorkspaceResponse } from "./DeleteWorkspaceResponse";
