// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceRecord } from "./WorkspaceRecord";

export type WorkspaceListResponse = { items: Array<WorkspaceRecord>, total: number, };
