// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkspaceRecord = { id: string, name: string, rootPath: string, note: string, createdAt: string, };
